workflows:
  snore-detector-ios-watch:
    name: Snore Detector (iOS + WatchOS)
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      # 保留你指定的 Xcode 16.0（若后续提示不支持，再改成15.3）
      xcode: 16.0
      cocoapods: default
    scripts:
    #先下载 xcodegen
      - name: Install xcodegen
        script: |
          brew install xcodegen
    #CodeMagic 中添加「前置脚本」，云端生成基础 Xcode 项目：在 codemagic.yaml 的 scripts 开头新增
      - name: Generate Xcode project (云端)
        script: |
          # 【仅改这里】把管道临时文件改成本地文件，解决权限拒绝问题
          cat > snore_detector_spec.yml << EOF
          name: SnoreDetector
          targets:
            SnoreDetector:
              type: application
              platform: iOS
              deploymentTarget: 15.0
              sources:
                - SnoreDetector
              infoPlist:
                path: SnoreDetector/Info.plist
                properties:
                  NSMicrophoneUsageDescription: "需要麦克风权限监测呼噜声"
                  UIBackgroundModes:
                    - audio
              capabilities:
                - name: watchConnectivity
            SnoreDetector Watch App:
              type: watch2app
              platform: watchOS
              deploymentTarget: 8.0
              sources:
                - SnoreDetector Watch App
              infoPlist:
                path: SnoreDetector Watch App/Info.plist
              dependencies:
                - target: SnoreDetector
          EOF
          # 用本地spec文件生成项目，替代原管道方式
          xcodegen generate --spec snore_detector_spec.yml
      # 步骤1：安装依赖（无 Pod 则跳过）
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      # 步骤2：设置签名（免费个人账号自动签名）
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      # 步骤3：构建 iOS + WatchOS 项目
      - name: Build iOS & WatchOS app
        script: |
          # 【仅改这里】xcodegen生成的是.xcodeproj，不是.xcworkspace，替换workspace为project
          xcodebuild -project "SnoreDetector.xcodeproj" \
                     -scheme "SnoreDetector" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath build/SnoreDetector.xcarchive \
                     archive CODE_SIGN_STYLE=Automatic \
                     DEVELOPMENT_TEAM=$(xcode-project get-team-id)
      # 步骤4：导出 IPA 文件（用于安装到真机）
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/SnoreDetector.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist <(cat <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>$(xcode-project get-team-id)</string>
              <key>compileBitcode</key>
              <false/>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          )
    # 输出构建产物（IPA 文件）
    artifacts:
      - build/ipa/*.ipa
      - build/SnoreDetector.xcarchive
    # 发布配置（支持直装链接/TestFlight）
    publishing:
      # 生成直装链接（手机打开即可安装）
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_API_KEY
      #   api_key_id: $APP_STORE_CONNECT_API_KEY_ID
      #   api_key_issuer_id: $APP_STORE_CONNECT_API_KEY_ISSUER_ID
      #   submit_to_testflight: false
      # 发送构建结果到邮箱
      email:
        recipients:
          - 2994574297@qq.com # 保留你的邮箱