workflows:
  snore-detector-ios-watch:
    name: Snore Detector (iOS + WatchOS)
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      xcode: 16.0
      cocoapods: default
    scripts:
      # 步骤1：升级xcodegen到最新版（解决类型识别问题）
      - name: Install/Upgrade xcodegen
        script: |
          brew uninstall --force xcodegen || true
          brew install xcodegen
          xcodegen --version # 验证版本，便于调试
      
      # 步骤2：生成Xcode项目配置文件 + 生成项目
      - name: Generate Xcode project (云端)
        script: |
          # 写入xcodegen配置文件（修复WatchOS类型 + 完善依赖）
          cat > snore_detector_spec.yml << EOF
          name: SnoreDetector
          targets:
            SnoreDetector:
              type: application
              platform: iOS
              deploymentTarget: 15.0
              sources:
                - SnoreDetector
              infoPlist:
                path: SnoreDetector/Info.plist
                properties:
                  NSMicrophoneUsageDescription: "需要麦克风权限监测呼噜声"
                  UIBackgroundModes:
                    - audio
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.snoredetector.ios
              capabilities:
                - name: watchConnectivity
              dependencies:
                - target: SnoreDetector Watch App
                  embed: true
            SnoreDetector Watch App:
              type: application.watchapp2
              platform: watchOS
              deploymentTarget: 8.0
              sources:
                - SnoreDetector Watch App
              infoPlist:
                path: SnoreDetector Watch App/Info.plist
              dependencies:
                - target: SnoreDetector Watch Extension
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.snoredetector.watchapp
                  WK_COMPANION_APP_BUNDLE_IDENTIFIER: com.snoredetector.ios
            SnoreDetector Watch Extension:
              type: watchkit2-extension
              platform: watchOS
              deploymentTarget: 8.0
              sources:
                - SnoreDetector Watch Extension
              infoPlist:
                path: SnoreDetector Watch Extension/Info.plist
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.snoredetector.watchextension
          EOF
          # 生成Xcode项目
          xcodegen generate --spec snore_detector_spec.yml
      
      # 步骤3：安装依赖（无Pod则跳过，保留兼容）
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      
      # 步骤4：配置代码签名（免费账号自动签名）
      - name: Set up code signing
        script: |
          xcode-project use-profiles
          TEAM_ID="$DEVELOPMENT_TEAM_ID"
          if [ -z "$TEAM_ID" ]; then
            echo "未配置 DEVELOPMENT_TEAM_ID：将改为仅做 iOS Simulator 编译/测试（不签名、不导出 IPA）。"
            echo "SKIP_ARCHIVE=1" >> $CM_ENV
            exit 0
          fi
          echo "Using DEVELOPMENT_TEAM=$TEAM_ID"
          echo "TEAM_ID=$TEAM_ID" >> $CM_ENV
      
      # 步骤5：构建iOS+WatchOS项目（Debug版，便于真机调试）
      - name: Build iOS & WatchOS app (Debug)
        script: |
          if [ "$SKIP_ARCHIVE" = "1" ]; then
            xcodebuild -project "SnoreDetector.xcodeproj" \
                       -scheme "SnoreDetector" \
                       -configuration Debug \
                       -destination 'platform=iOS Simulator,name=iPhone 15' \
                       clean test \
                       CODE_SIGNING_ALLOWED=NO \
                       CODE_SIGNING_REQUIRED=NO \
                       CODE_SIGN_IDENTITY="" \
                       COMPILER_INDEX_STORE_ENABLE=NO
            exit 0
          fi
          xcodebuild -project "SnoreDetector.xcodeproj" \
                     -scheme "SnoreDetector" \
                     -configuration Debug \
                     -destination 'generic/platform=iOS' \
                     -archivePath build/SnoreDetector-Debug.xcarchive \
                     archive CODE_SIGN_STYLE=Automatic \
                     DEVELOPMENT_TEAM="$TEAM_ID" \
                     COMPILER_INDEX_STORE_ENABLE=NO # 关闭索引，加速构建
      
      # 步骤6：导出可安装的IPA（Debug版，支持真机调试）
      - name: Export IPA (Debug)
        script: |
          if [ "$SKIP_ARCHIVE" = "1" ]; then
            echo "跳过导出 IPA：未配置 DEVELOPMENT_TEAM_ID。"
            exit 0
          fi
          xcodebuild -exportArchive \
                     -archivePath build/SnoreDetector-Debug.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist <(cat <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
              <key>allowProvisioningUpdates</key>
              <true/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          )
    # 构建产物（IPA和归档文件）
    artifacts:
      - build/ipa/*.ipa
      - build/SnoreDetector-Debug.xcarchive
    # 发布配置（邮件通知 + 可选TestFlight）
    publishing:
      email:
        recipients:
          - 2994574297@qq.com
      # 如需自动上传TestFlight，取消注释并配置环境变量
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_API_KEY
      #   api_key_id: $APP_STORE_CONNECT_API_KEY_ID
      #   api_key_issuer_id: $APP_STORE_CONNECT_API_KEY_ISSUER_ID
      #   submit_to_testflight: true

  snore-detector-ci-check:
    name: Snore Detector (CI Check, No Codesign)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install/Upgrade xcodegen
        script: |
          brew uninstall --force xcodegen || true
          brew install xcodegen
          xcodegen --version

      - name: Generate Xcode project (云端)
        script: |
          cat > snore_detector_spec.yml << EOF
          name: SnoreDetector
          targets:
            SnoreDetector:
              type: application
              platform: iOS
              deploymentTarget: 15.0
              sources:
                - SnoreDetector
              infoPlist:
                path: SnoreDetector/Info.plist
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.snoredetector.ios
              capabilities:
                - name: watchConnectivity
              dependencies:
                - target: SnoreDetector Watch App
                  embed: true
            SnoreDetector Watch App:
              type: application.watchapp2
              platform: watchOS
              deploymentTarget: 8.0
              sources:
                - SnoreDetector Watch App
              infoPlist:
                path: SnoreDetector Watch App/Info.plist
              dependencies:
                - target: SnoreDetector Watch Extension
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.snoredetector.watchapp
                  WK_COMPANION_APP_BUNDLE_IDENTIFIER: com.snoredetector.ios
            SnoreDetector Watch Extension:
              type: watchkit2-extension
              platform: watchOS
              deploymentTarget: 8.0
              sources:
                - SnoreDetector Watch Extension
              infoPlist:
                path: SnoreDetector Watch Extension/Info.plist
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.snoredetector.watchextension
          EOF
          xcodegen generate --spec snore_detector_spec.yml

      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build & Test (iOS Simulator, No Codesign)
        script: |
          xcodebuild -project "SnoreDetector.xcodeproj" \
                     -scheme "SnoreDetector" \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     clean test \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     COMPILER_INDEX_STORE_ENABLE=NO